# src/ocr_worker.py
# Background thread that processes images through the OCR AI model.
# Handles streaming output and parses grounding tags for bounding boxes.

import time
import re
from PySide6.QtCore import QThread, Signal
from ollama_service import stream_ocr_response
import file_handler
import config


class OCRWorker(QThread):
    """
    Worker thread that processes a queue of images through DeepSeek-OCR.

    Signals (events emitted to notify the main UI thread):
    - stream_chunk: Emits text as it's generated by DeepSeek-OCR
    - image_started: Emits when starting to process a new image
    - image_finished: Emits when done with an image (includes duration)
    - finished_all: Emits when entire queue is processed
    - error_occurred: Emits error messages
    - box_detected: Emits bounding box coordinates [x1, y1, x2, y2]
    """
    stream_chunk = Signal(str)
    image_started = Signal(str, int)
    image_finished = Signal(str, float)
    finished_all = Signal()
    error_occurred = Signal(str)
    box_detected = Signal(list)

    def __init__(self, client, queue_items, prompt, model_name, prompt_id=None):
        super().__init__()
        self.client = client
        self.queue_items = queue_items 
        self.prompt = prompt
        self.model_name = model_name
        self.prompt_id = prompt_id
        self.is_running = True 

        """
        Grounding mode determines how to handle grounding tags:
        - 'markdown': Suppress <|ref|> content (useless metadata)
        - 'ocr': Emit <|ref|> content (it contains actual OCR text)
        - None: Passthrough mode, no tag processing
        """
        if prompt_id == 'p_markdown':
            self.grounding_mode = 'markdown'
        elif prompt_id == 'p_ocr':
            self.grounding_mode = 'ocr'
        else:
            self.grounding_mode = None

        # Regex patterns for parsing grounding tags from AI output
        # REF tags: <|ref|>text content<|/ref|> - contains recognized text
        self.pattern_ref = re.compile(r"<\|ref\|>(.*?)<\|/ref\|>")
        # DET tags: <|det|>[[x1,y1,x2,y2]]<|/det|> - contains bounding box coordinates
        self.pattern_det = re.compile(r"<\|det\|>\[\[(.*?)\]\].*?<\|/det\|>")

        self.buffer = ""  # Accumulates streamed text for tag parsing
        self.has_seen_tags = False

    def run(self):
        # Main thread execution - processes each image in the queue
        try:
            for i, (display_name, filepath, page_index) in enumerate(self.queue_items):
                if not self.is_running: break 

                self.image_started.emit(display_name, i)

                start_time = time.time()
                try:
                    if page_index == -1:
                        # Regular image file
                        img_bytes = file_handler.get_image_bytes(filepath)
                    else:
                        # PDF page (page_index is 0-based)
                        img_bytes = file_handler.extract_pdf_page_bytes(filepath, page_index)
                except Exception as e:
                    self.error_occurred.emit(f"Failed to load {display_name}: {e}")
                    continue

                # Process each chunk from the streaming AI response
                self.buffer = ""
                for chunk in stream_ocr_response(self.client, self.model_name, self.prompt, img_bytes, config.INFERENCE_PARAMS):
                    if not self.is_running: break 
                    self.process_chunk(chunk)

                # Flush any remaining text in buffer
                if self.buffer:
                    self.stream_chunk.emit(self.buffer)
                    self.buffer = ""

                duration = time.time() - start_time

                # Explicitly delete image bytes to free RAM immediately
                del img_bytes 

                if not self.is_running: break
                self.image_finished.emit(display_name, duration)

            self.finished_all.emit()

        except Exception as e:
            self.error_occurred.emit(str(e))

    def process_chunk(self, chunk):
        """
        Processes a chunk of streaming text from the AI.

        In passthrough mode: directly emits all text.
        In grounding mode: parses <|ref|> and <|det|> tags, extracting
        bounding boxes and filtering output based on mode.
        """
        # Passthrough mode: no grounding tags expected, emit directly
        if self.grounding_mode is None:
            self.stream_chunk.emit(chunk)
            return

        self.buffer += chunk

        # Loop to process all complete tags in buffer
        while True:
            # Search for both tag types
            match_ref = self.pattern_ref.search(self.buffer)
            match_det = self.pattern_det.search(self.buffer)

            # Determine which tag appears first in the buffer
            first_match = None
            match_type = None

            if match_ref and match_det:
                if match_ref.start() < match_det.start():
                    first_match = match_ref
                    match_type = 'ref'
                else:
                    first_match = match_det
                    match_type = 'det'
            elif match_ref:
                first_match = match_ref
                match_type = 'ref'
            elif match_det:
                first_match = match_det
                match_type = 'det'
            else:
                break  # No complete tags found, exit loop

            self.has_seen_tags = True 

            start, end = first_match.span()

            # Emit any text that appears before the tag
            prefix = self.buffer[:start]
            if prefix:
                self.stream_chunk.emit(prefix)

            if match_type == 'ref':
                ref_text = first_match.group(1)
                # In 'ocr' mode, ref tags contain the actual OCR text - emit it
                # In 'markdown' mode, ref tags are metadata - suppress
                if self.grounding_mode == 'ocr' and ref_text:
                    self.stream_chunk.emit(ref_text)

            elif match_type == 'det':
                # Parse bounding box coordinates from det tag
                det_coords_str = first_match.group(1)
                try:
                    coords = [int(x.strip()) for x in det_coords_str.split(',')]
                    if len(coords) == 4:
                        self.box_detected.emit(coords)
                except ValueError:
                    pass  # Invalid coordinates, ignore

            # Remove processed tag from buffer
            self.buffer = self.buffer[end:]

        # === Buffer flushing logic ===
        # Prevents stuttering by immediately emitting "safe" text while
        # holding back potential incomplete tags
        MAX_BUFFER_SIZE = 1000

        # Find the last '<' character - could be start of a grounding tag
        last_open_angle = self.buffer.rfind("<")

        if last_open_angle == -1:
            # No '<' found - safe to emit entire buffer
            self.stream_chunk.emit(self.buffer)
            self.buffer = ""
        else:
            tail = self.buffer[last_open_angle:]

            # Only wait if the tail could become a grounding tag
            VALID_STARTS = ["<|ref|>", "<|det|>"]

            is_dangerous = False

            for tag_start in VALID_STARTS:
                # Case 1: tail is a prefix of a tag (e.g. "<", "<|", "<|r")
                # We must wait to see if it completes into a full tag
                if tag_start.startswith(tail):
                    is_dangerous = True
                    break

                # Case 2: tail starts with a complete tag opening
                # We're inside the tag, waiting for closing sequence
                if tail.startswith(tag_start):
                    is_dangerous = True
                    break

            if is_dangerous:
                # Keep the tail in buffer, emit everything before it
                safe_part = self.buffer[:last_open_angle]
                if safe_part:
                    self.stream_chunk.emit(safe_part)
                self.buffer = tail
            else:
                # The '<' is not a grounding tag - safe to emit all
                self.stream_chunk.emit(self.buffer)
                self.buffer = ""

            # Emergency flush if buffer gets too large
            if len(self.buffer) > MAX_BUFFER_SIZE:
                self.stream_chunk.emit(self.buffer)
                self.buffer = ""

    def stop(self):
        # Request the worker to stop processing (checked between images)
        self.is_running = False
