# src/transformers_service.py
import sys
import threading
import queue
import torch
import gc
import os
from transformers import AutoModel, AutoTokenizer
from PySide6.QtCore import QThread, Signal
import config

# Global state to hold the model instance
_model = None
_tokenizer = None

def load_model_if_needed():
    global _model, _tokenizer
    if _model is not None:
        return True

    try:
        import warnings
        import transformers
        warnings.filterwarnings("ignore")
        transformers.logging.set_verbosity_error()

        model_path = "Dogacel/Universal-DeepSeek-OCR-2"
        _tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)

        kwargs = {
            "trust_remote_code": True,
            "use_safetensors": True
        }

        # Use Flash Attention 2 only if CUDA is available, otherwise fallback to eager
        if torch.cuda.is_available():
            device = "cuda"
            kwargs["torch_dtype"] = torch.bfloat16
            kwargs["_attn_implementation"] = "flash_attention_2"
        elif hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
            device = "mps"
            kwargs["torch_dtype"] = torch.float16
            kwargs["attn_implementation"] = "eager"
        else:
            device = "cpu"
            kwargs["torch_dtype"] = torch.float16
            kwargs["attn_implementation"] = "eager"

        _model = AutoModel.from_pretrained(model_path, **kwargs)
        _model = _model.eval().to(device)

        # --- MONKEY PATCH NoEOSTextStreamer ---
        # The model uses TextStreamer which aggressively buffers characters until a space or newline.
        # This causes the UI to freeze during long LaTeX math equations (\[ ... \]) which have no spaces.
        # We patch it to flush immediately on every token.
        import sys
        model_module = sys.modules[_model.__class__.__module__]

        def patched_put(self, value):
            if len(value.shape) > 1 and value.shape[0] > 1:
                raise ValueError("TextStreamer only supports batch size 1")
            elif len(value.shape) > 1:
                value = value[0]

            if self.skip_prompt and self.next_tokens_are_prompt:
                self.next_tokens_are_prompt = False
                return

            self.token_cache.extend(value.tolist())
            text = self.tokenizer.decode(self.token_cache, **self.decode_kwargs)

            # Don't flush if it ends with an incomplete unicode replacement char
            if text.endswith("\ufffd"):
                return

            printable_text = text[self.print_len:]
            self.print_len += len(printable_text)
            self.on_finalized_text(printable_text)

            # Clear cache on newline to prevent memory buildup
            if text.endswith("\n"):
                self.token_cache = []
                self.print_len = 0

        model_module.NoEOSTextStreamer.put = patched_put

        return True
    except Exception as e:
        print(f"Error loading model: {e}")
        return False

def unload_model():
    global _model, _tokenizer
    if _model is not None:
        del _model
        del _tokenizer
        _model = None
        _tokenizer = None
        torch.cuda.empty_cache()
        gc.collect()
        return True
    return False

def stream_ocr_response(prompt: str, image_file: str):
    """
    Generator that intercepts sys.stdout and yields tokens generated by model.infer().
    """
    if _model is None:
        raise RuntimeError("Model is not loaded. Call load_model_if_needed() first.")

    output_queue = queue.Queue()

    class StreamCapture:
        def __init__(self, q):
            self.q = q
        def write(self, text):
            self.q.put(text)
        def flush(self):
            pass

    original_stdout = sys.stdout
    capture = StreamCapture(output_queue)
    sys.stdout = capture

    # Create output directory for crops if it doesn't exist
    if not os.path.exists(config.OUTPUT_DIR):
        os.makedirs(config.OUTPUT_DIR)

    def run_inference():
        try:
            _model.infer(
                tokenizer=_tokenizer, 
                prompt=prompt, 
                image_file=image_file, 
                output_path=config.OUTPUT_DIR,
                base_size=1024, 
                image_size=768, 
                crop_mode=True,
                save_results=False,
                device=_model.device.type,
                dtype=_model.dtype
            )
        except Exception as e:
            # We write errors to stderr so they don't get caught by stdout stream
            print(f"Error during inference: {e}", file=sys.stderr)
        finally:
            output_queue.put(None) # Sentinel to signal end

    thread = threading.Thread(target=run_inference)
    thread.start()

    debug_filters = ['PATCHES:', 'BASE:', 'directly resize', 'NO PATCHES', 'torch.Size', 'Loading']
    has_started_content = False

    while True:
        chunk = output_queue.get()
        if chunk is None:
            break

        # A standard Python print() usually sends the string + \n in one write() call, 
        # or at least the string itself in one chunk. We filter these exact chunks.
        if any(s in chunk for s in debug_filters):
            continue
            
        # DeepSeek prints exactly 21 equals signs as a separator
        if chunk.strip() == "=====================":
            continue

        # Swallow lingering newlines from the filtered print() statements 
        # until the actual model output begins.
        if not has_started_content:
            if not chunk.strip():
                continue
            has_started_content = True
            chunk = chunk.lstrip()

        yield chunk

    sys.stdout = original_stdout


class PreCheckWorker(QThread):
    # Background thread to check connection and load model before processing.
    # Emits (success, error_type, error_msg)
    # error_type: 'model' or None if success
    finished = Signal(bool, str, str)

    def __init__(self):
        super().__init__()

    def run(self):
        success = load_model_if_needed()
        if not success:
            self.finished.emit(False, 'model', "Failed to load DeepSeek-OCR-2 into memory. Check console for details.")
            return

        self.finished.emit(True, '', '')


class ModelUnloadWorker(QThread):
    # Background thread to unload the AI model from GPU memory.
    finished = Signal(bool, str)  # (success, message_key_or_error)

    def __init__(self):
        super().__init__()

    def run(self):
        global _model
        if _model is not None:
            unload_model()
            self.finished.emit(True, "msg_model_unloaded")
        else:
            self.finished.emit(True, "msg_model_not_loaded")
